name: Frontend CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # @link https://github.com/actions/checkout
      - name: Checkout do código
        uses: actions/checkout@v3

      # Para aplicações com Node, veja:
      # https://github.com/actions/setup-node
      - name: Build da aplicação
        run: <comando>

      - name: Teste da aplicação
        run: <comando>